### ISSUE TITLE
OpentK.dll.config ist veraltet

### ISSUE THREAD

**Issue by XYZLassi** [jvbsl/engenious#18]
Hallo,
die StandardConfig-Datei für opentk ist veraltet.

**Comment by jvbsl** [comment]
Inwiefern, ich hab sie schonmal absichtlich abgeändert, weil er sonst Probleme beim laden von ein paar libraries hatte(zumindest bei mir)

**Comment by XYZLassi** [comment]
Es fehlte bei mir der Eintrag für die SDL2.dll und ohne den startet es bei mir erst recht nicht. Hast du die entfernt ??
[OpenTK.dll.config.txt](https://github.com/OctoAwesome/engenious/files/719855/OpenTK.dll.config.txt)

**Comment by jvbsl** [comment]
jop, mit dem Eintrag startet es bei mir nicht

**Comment by XYZLassi** [comment]
Da müssen wir mal schaun woran das liegt
hast du das Package installiert ???

**Comment by fnawratil** [comment]
Ist das noch aktuell?

**Comment by jvbsl** [comment]
nutzen jetzt die version von OpenTK
