### ISSUE TITLE
Engenious rendert Falsch 

### ISSUE THREAD

**Issue by XYZLassi** [jvbsl/engenious#20]
So wird bei mir gerade OctoAwesome gerendert in der Version 0.1.1 und 0.1.7 von Engenious.

![bildschirmfoto vom 2017-01-27 13-08-26](https://cloud.githubusercontent.com/assets/12987399/22370475/dd64d228-e491-11e6-8fa9-749015a967d2.png)

**Comment by XYZLassi** [comment]
Also @jvbsl wenn du mal Zeit hab muss ich dir das mal bei Teamviewer zeigen

**Comment by jvbsl** [comment]
war wohl nichts mit dem Update, muss ich mir mal angucken
Tritt das Problem bei älteren Versionen auch auf?

**Comment by jvbsl** [comment]
ohh, habs überlesen, dass es auch schon bei 0.1.1 bei dir so ist. Das ist allerdings äußerst komisch, bei mir funktionierts bei beiden und sogar auf Windows scheints zu funktionieren, da muss man glaub ich einmal richtig durchdebuggen -.-

**Comment by fnawratil** [comment]
Besteht der Fehler noch?

**Comment by jvbsl** [comment]
sollte nicht mehr passieren
should be fixed...
