### ISSUE TITLE
Crash on file delete

### ISSUE THREAD

**Issue by fnawratil** [jvbsl/engenious#22]
The ContentTool crashes when an included file can't be found / is deleted

**Comment by jvbsl** [comment]
FUU du hast da ja was commited :D ich jetzt auch, kann man sich ja aussuchen :D

**Comment by fnawratil** [comment]
Beide passen. Du fixt das Problem wenn das File beim Builden nicht da ist, ich wenn der Nutzer einfach nur im Tree draufklickt
