### ISSUE TITLE
Fix lovely CI

### ISSUE THREAD

**Issue by jvbsl** [jvbsl/engenious#24]
CI has problems cause of GitVersion(perhaps remove it?)

**Comment by fnawratil** [comment]
Could you please watch your language?! 😛

**Comment by fnawratil** [comment]
AppVeyor fixed

**Comment by fnawratil** [comment]
CI fixed :)

**Comment by jvbsl** [comment]
not really sure If I like your fix, why you need to define everything separately from the normal build process? perhaps some one just wants to run build.sh without using an IDE, but then it's not CI even if it's called that way?

**Comment by fnawratil** [comment]
Well, we could simply supply build.sh with the Configuration. I'll implement this

**Comment by jvbsl** [comment]
but I still don't see the point of seperated configurations

**Comment by fnawratil** [comment]
This is needed as the ContentTool currently cannot run without any Monitor. Don't ask me why...
